import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import GlobalProvider from './context/GlobalContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
        <main className={'lg:px-28 md:px-24 sm:px-20 xs:px-14 xxs:px-8 bg-[#f6f7fb]'}>
          <Header />
          {children}
        </main>
        </GlobalProvider>
      </body>
    </html>
  )
}
